### PR TITLE
Fix the options page issue in WP prior to 4.7

### LINKED ISSUE #1095: Fatal error in WordPress 3.8
Since it's mentioned in the plugin readme that WP 3.8 is supported, so I set the required version for my plugin to be 3.8. But, when I tested it on that version, it crashed.
**Fatal Error: Call to undefined function register_setting() in `/public_html/wp-content/plugins/cmb2/includes/CMB2_Options_Hookup.php on line 49`**

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Fixes #1095 and adds options page support for WP prior to 4.7, which otherwise crashed because of `register_setting` function been moved to `/wp-includes/option.php` in WP 4.7 because of [this](https://core.trac.wordpress.org/ticket/37885).

### CODE REVIEW

File: includes/CMB2_Options_Hookup.php [hunk 1]
```diff
@@ -50,6 +50,17 @@ public function hooks() {
 			add_filter( "cmb2_should_autoload_{$this->option_key}", '__return_false' );
 		}
 
+		/**
+		 * for WP < 4.7
+		 *
+		 * @see https://core.trac.wordpress.org/ticket/37885
+		 */
+		global $wp_version;
+		if ( version_compare( $wp_version, '4.7', '<' ) ) {
```
Comment (jtsternberg) [inline includes/CMB2_Options_Hookup.php]: Let's use `if ( ! CMB2_Utils::wp_at_least( '4.7' ) && ! function_exists( 'register_setting' ) ) {`, but this looks good.

Comment (manzoorwanijk) [reply includes/CMB2_Options_Hookup.php]: yes, that's off course better :)

Comment (manzoorwanijk) [reply includes/CMB2_Options_Hookup.php]: Yes, I tested it for all: WP < 4.7, = 4.7 > 4.7.

**Comment by jtsternberg** [comment]
Thanks again for your contribution. We very much appreciate it!
